create table CB_RECOLTE (ID integer not null auto_increment, AMOUNT double precision, DATE_OPERATION date, primary key (ID))
create table MONEY_TYPE (CODE varchar(255) not null, DESCRIPTION varchar(255), primary key (CODE))
create table ROLE (ID integer not null auto_increment, DESCRIPTION varchar(255), NAME varchar(255), primary key (ID))
create table SALE_DATA (DATE_OPERATION date not null, SERVER_ID integer not null, AMOUNT_10_TAXES double precision, AMOUNT_20_TAXES double precision, IS_LOCKED bit, NB_COUVERT integer, primary key (DATE_OPERATION, SERVER_ID))
create table SALE_DETAILS (ID integer not null auto_increment, AMOUNT double precision, DATE_OPERATION date, QTY integer, PAYMENT_TYPE_ID varchar(255) not null, SERVER_ID integer not null, primary key (ID))
create table SERVER (ID integer not null auto_increment, FIRST_NAME varchar(255), LAST_NAME varchar(255), primary key (ID))
create table USER (ID integer not null auto_increment, NAME varchar(255), PASSWORD varchar(255), primary key (ID))
create table USER_ROLE (USER_ID integer not null, ROLE_ID integer not null)
alter table SALE_DETAILS add constraint FK_arq2wa7633rry83i4wekijf70 foreign key (PAYMENT_TYPE_ID) references MONEY_TYPE (CODE)
alter table SALE_DETAILS add constraint FK_ecfsopqw3qawgoicilye5v693 foreign key (SERVER_ID) references SERVER (ID)
alter table USER_ROLE add constraint FK_oqmdk7xj0ainhxpvi79fkaq3y foreign key (ROLE_ID) references ROLE (ID)
alter table USER_ROLE add constraint FK_j2j8kpywaghe8i36swcxv8784 foreign key (USER_ID) references USER (ID)
