INSERT INTO ROLE(ID, NAME, DESCRIPTION) VALUES(1, 'ADMIN', 'ADMIN');
INSERT INTO ROLE(ID, NAME, DESCRIPTION) VALUES(2, 'SAISIE', 'SAISIE CAISSE');
INSERT INTO ROLE(ID, NAME, DESCRIPTION) VALUES(3, 'VISU_TR', 'VISUALISATION TR');

-- Compte 1
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);

-- Compte 2
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(2, 1);

-- Compte 3
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(3, 3);

-- Compte 4
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(4, 3);

INSERT INTO MONEY_TYPE (CODE, DESCRIPTION) VALUES('ESPECES', 'ESPECES');
INSERT INTO MONEY_TYPE (CODE, DESCRIPTION) VALUES('CHEQUE_BANCAIRE', 'CHEQUE BANCAIRE');
INSERT INTO MONEY_TYPE (CODE, DESCRIPTION) VALUES('TICKET_RESTAURANT', 'TICKET RESTAURANT');
INSERT INTO MONEY_TYPE (CODE, DESCRIPTION) VALUES('BON_COMMANDE', 'BON DE COMMANDE');
INSERT INTO MONEY_TYPE (CODE, DESCRIPTION) VALUES('CARTE_BANCAIRE', 'CARTE BANCAIRE');
